Store api-key values in hashed format
balena-io/pinejs pull request #158
Opened 2018-04-23 23:11 UTC by afitzek

This stores the api key values as sha256 hashes. The database values are prefixed with 'SHA256:HEX:' to indicate, which hash algorithm and which encoding are used.

Depends-On: https://github.com/resin-io-modules/sbvr-types/pull/14
Change-Type: major
Signed-off-by: Andreas Fitzek <andreas@resin.io>

2018-04-24 15:11 UTC, flesler approved these changes
The change looks OK but I really wonder if there are other people where this will impact, I expect some to be.

2018-04-25 05:18 UTC, Page- requested changes
Can you add a template migration that can be used for the major upgrade

2018-04-27 20:47 UTC, dfunckt commented
@afitzek please let’s discuss what we’re going to do with the delta server before merging this, this is a serious blocker for the new deltas.

2018-05-05 00:15 UTC, Page- commented on src/sbvr-api/sbvr-utils.coffee
> +exports.hashApiKey = permissions.hashApiKey
Everything from `permissions` is already exported below via an `_.extend(exports, permissions)`

2021-04-01 16:05 UTC, petrosagg reviewed
No-op review to dismiss stale review request

2026-05-11 08:08 UTC, closed without merging